### PR TITLE
Update Composer checks to work with Laravel 5.8

### LINKED ISSUE #75: Composer::installDryRun() calling getProcess without argument
```
Too few arguments to function Illuminate\Support\Composer::getProcess(), 0 passed in /vendor/beyondcode/laravel-self-diagnosis/src/Composer.php on line 9 and exactly 1 expected
```

Looks like Laravel 5.8 changed `Illuminate\Support\Composer::getProcess()` to have a required `array $command` argument.

### PR DESCRIPTION
**Pull request by fitztrev**
In Laravel 5.8, `Composer::getProcess()` now requires the `$command` passed to it as an array.

Also in 5.8, `Composer::findComposer()` now returns an array instead of a string. So I'm using that to determine which `->getProcess()` is called. Should be compatible with 5.7.

Change commit in Laravel: laravel/framework@d1b948103b9933d9881c280df39b289f324bcceb

Fixes #75, ping @kbond

### CODE REVIEW

**Comment by fitztrev** [comment]
Ping @mpociot, this is needed for 5.8 compatibility.

File: src/Composer.php [hunk 1]
```diff
@@ -6,9 +6,20 @@ class Composer extends \Illuminate\Support\Composer
...
     public function installDryRun(string $options = null)
     {
-        $process = $this->getProcess();
+        $composer = $this->findComposer();
 
-        $process->setCommandLine(trim($this->findComposer().' install --dry-run '.$options));
+        $command = array_merge(
+            (array) $composer,
+            ['install', '--dry-run'],
+            array_filter(array_map('trim', explode(' ', $options))),
```
Comment (eristemena) [inline src/Composer.php]: That last comma gives me error,

```
ParseError::("syntax error, unexpected ')'")
      /c/htdocs/dodol/vendor/beyondcode/laravel-self-diagnosis/src/Composer.php:15
```

Comment (fitztrev) [reply src/Composer.php]: Fixed. Thanks

**Comment by fitztrev** [comment]
Ping @mpociot
